{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Среднее время ответа запроса (сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m])/rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[1m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_virtual_memory_bytes[1m])/(31.34*1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество предсказаний",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Предсказания за 10 мин",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(main_app_predictions_bucket{le!=\"+Inf\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество предсказаний (bins)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(main_app_predictions_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}