{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Среднее кол-во запросов, ед/сек",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_flats_request_counter_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение предсказаний, %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(app_flats_price_predictions_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_resident_memory_bytes[1m]) / process_virtual_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время задержки",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_highr_seconds_sum[1m]) / rate(http_request_duration_highr_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доля ошибок, %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(app_flats_error_counter_total[1m]) / increase(app_flats_request_counter_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}