FROM python:3.11-slim

LABEL author=${AUTHOR}

COPY ./ml_service/flats_app.py ./services/ml_service/flats_app.py
COPY ./ml_service/flats_handler.py ./services/ml_service/flats_handler.py
COPY ./models/flats ./services/models/flats
COPY requirements.txt ./services/requirements.txt

WORKDIR services
RUN pip3 install -r requirements.txt

EXPOSE ${APP_PORT}
CMD uvicorn ml_service.flats_app:app --host 0.0.0.0 --port ${APP_PORT}
